### ISSUE TITLE
Service listing available templates

### ISSUE THREAD

**Issue by microstudi** [aFFaC-cat/decidim-affac#9]
- [ ] Create a service/form to obtain templates from the disk, stored in YAML format.
A template might be organized as follows in the disk:
```
lib/templates/template-1.yml
lib/templates/template-2.yml
lib/templates/template-1/file1.png
```
Some service/helper should list all the available templates for their subsequent use in a decidim Form.
For instance:
```ruby
templates = OrganizationTemplates.all
```
A template must consist of a single YAML file with optional files referenced in it, the definitive format might change depending on the needs once creating it. Here is a suggestion:

```yaml
vars:
  organization_title: translated_string
  ref: string
id: template-1
spaces:
  - manifest: consultations
    title: 
      ca: Consulta per %{organization_title}
      es: Consulta para %{organization_title}
    cover: template-1/file1.png
```

The `vars` section will be used
